### PR TITLE
implement logging

### PR DESCRIPTION
**Pull request by silviuFlorin**

### CODE REVIEW

**Comment by mwobensmith** [comment]
This is almost perfect the way it is. 

I have one question. How do we specify a custom path for the log file? I see that it is specified in logging.ini, but when I ran this, it saved the log file to the last folder that I opened, which can be pretty random. I assume that it just picks up the current working directory as a default, but that will be different for each person working on the project. Is there any way we can control this?

**Comment by silviuFlorin** [comment]
The mode for FileHandler is 'a' , which means that if the log file exists it would open it and start appending to it at the end, otherwise it would create the file

To save it in another location we have to provide the path to the file:
`args=("log/iris_log.log", 'a', 99999, 10)`

But the FileHandler would only create the log file if it does not exist , it would not create the directory if that does not exist and it would throw an error

You would need to create the directory yourself , either manually or programatically (using os.makedirs() )

**Comment by mwobensmith** [comment]
OK, so how would you put the log file in the root of our project, without hard-coding the path here? The actual directory will vary based on your username and platform, so you would have to figure it out programmatically, i.e.:

C:\Users\USERNAME\iris\iris_log.log
~/iris/iris_log

**Comment by silviuFlorin** [comment]
The log file is generated in the root of the project by default if no other path is provided. Do you have a use case where the log file is generated elsewhere?

**Pull request merged**
